version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: poc
    ports:
      - "15672:15672" # management
      - "5672:5672"   # AMQP
      - "1883:1883"   # MQTT
      - "61613:61613" # STOMP over ws
    environment:
       - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./config/definitions.json:/etc/rabbitmq/definitions.json

volumes:
  rabbitmq_data: